mysite/myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import BookList, DetailBooK, Mylogout, buysubag, categoris, categorychild, Mylogin, ghav, categoryfinal, infinity, mybooks, request_infinity, oldcomment, post_detail, popular_books_detail, hot_books_detail, SearchList, categoryrecent, Mysend, Login1, login2, login3,  Newu1, Mysend1, nasb, home, buy1, buy2, buy3, buy4, login4,  manageq, karnameh, detailbuy, pretebar,etebar, eshtbi, subscribe, buysub
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, PasswordResetConfirmView, PasswordChangeView, PasswordResetDoneView, PasswordResetView
from django.urls import reverse

app_name = 'myapp'

urlpatterns = [path('', BookList.as_view(), name='api'), 
path('', home, name='apii'),              

path('book/<slug:slug>', DetailBooK.as_view(), name='detail'),
path('categories', categoris, name='categoris'),   
path('categories/<slug:slug>', categorychild, name='categorychild'), 
path('categoriesfinal/<slug:slug>', categoryfinal, name='categoryfinal'),   
path('login/', Mylogin.as_view(), name='login' ),
path('ghav', ghav, name='ghav' ),
path('infinity/', infinity, name='infinity' ),
path('reinfinity/', request_infinity, name='reinfinity' ),
path('book/oldcomment/<slug:slug>', oldcomment, name='old_comment' ),
path('book/newcomment/<slug:slug>', post_detail, name='new_comment' ),
path('popularbooksdetail/', popular_books_detail, name='popular_books_detail' ),
path('mysend', Mysend.as_view(), name='mysend' ),
path('hotbooksdetail/', hot_books_detail, name='hot_books_detail' ),
path('search/', SearchList.as_view(), name='search'), 
path('book/pc', categoryrecent , name='categoryrecent'),
# path('login1/', Login1.as_view(), name='login1' ),
path('login2/', login2, name='login2' ),
path('login3/', login3, name='login3' ),
path('login4/', login4, name='login4' ),

path('newu1/', Newu1.as_view(), name='newu1' ),
path('mysend1', Mysend1.as_view(), name='mysend1' ),
path('install', nasb, name='nasb' ),
path('logout', Mylogout.as_view(), name='mylogout' ),
path('install', nasb, name='nasb' ),
path('sale/<slug:slug>', buy1, name='buy1' ),
path('sale2', buy2, name='buy2' ),
path('sale3', buy3, name='buy3' ),
path('sale4', buy4, name='buy4' ),
path('mybooks', mybooks, name='mybooks' ),
# path('buyhistory', buyhistory, name='buyhistory' ),
path('manageq', manageq, name='manageq' ),
path('readingreport', karnameh, name='karnameh' ),
path('detailbuy/<slug:slug>', detailbuy, name='detailbuy'),
path('pretebar', pretebar, name='pretebar' ),
path('etebar', etebar, name='etebar' ),
path('eshtbi', eshtbi, name='eshtbi' ),
path('subscribe/<slug:slug>', subscribe, name='subscribe'),
path('buysubag', buysubag, name='buysubag'),
path('buysub', buysub, name='buysub'),

]         

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView

from myapp.views import  Profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('mypass', PasswordResetView.as_view(), name="password_reset"),
path('mydone', PasswordResetDoneView.as_view(), name='password_reset_done' ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm"
    ),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),




# path('signup', signup, name='signup'),
path('profile', Profile.as_view(), name='profile'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/myapp/views.py
from dataclasses import Field, fields
import email
from email.policy import default
from enum import unique
import http
from turtle import position
from jalaliconv.utils import jalali_convertor
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate
from django.contrib import auth
import datetime
from django.shortcuts import redirect, render
from django.db.models import F

from ipaddress import ip_address
from tempfile import template
from django.shortcuts import get_object_or_404, render
from .models import Book, Category, Comment, numbers_convertor, BookHit, Getpass, Publication
# UserProfile

from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import SignupForm, SignuppForm, TestFormm, MyPasswordResetForm, MyForm, FinalForm, InfinityForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse
from star_ratings.models import UserRating

from django.contrib.auth.decorators import login_required

from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.sessions.models import Session

from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.forms import PasswordResetForm

from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags



from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.views import LoginView, PasswordResetConfirmView, PasswordChangeView, PasswordResetDoneView, PasswordResetView, LogoutView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView
from .models import User
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .forms import CommentForm
#from .forms import ProfileForm
from datetime import datetime, timedelta
from django.db.models import Count, Q
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from random import randint, randrange

from django.template.loader import render_to_string, get_template

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
#from .forms import SignupForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
#from .tokens import account_activation_token
import random 
from random import randrange
from .models import User
from django.db.models import Count, Q
from django.core.mail import EmailMessage
# Create your views here.
# 
# 
from django.shortcuts import render, get_object_or_404

# def post_detail(request, slug):
#     template_name = 'detail.html'
#     book = get_object_or_404(Book, slug=slug)
#     comments = book.comments.filter(active=True)
#     new_comment = None
#     # Comment posted
#     if request.method == 'POST':
#         comment_form = CommentForm(data=request.POST)
#         if comment_form.is_valid():

#             # Create Comment object but don't save to database yet
#             new_comment = comment_form.save(commit=False)
#             # Assign the current post to the comment
#             new_comment.book = book
#             # Save the comment to the database
#             new_comment.save()
#     else:
#         comment_form = CommentForm()

#     return render(request, template_name, {'book': book,
#                                            'comments': comments,
#                                            'new_comment': new_comment,
#                                            'comment_form': comment_form})
    
    
    

class BookList(ListView):
    model = Book
    
    queryset = Book.objects.filter(status='p')
    template_name = 'mybase.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        mybag = self.request.user.mybag

        # Add in a QuerySet of all the books
        context['mybag'] = mybag
        return context




 
def home(request) :
    mybag = request.user.mybag
    return render(request,'mybase2.html', {'mybag':mybag})
 
    

class DetailBooK(DetailView):
    template_name = 'detail.html'
    def get_object(self):
        slug = self.kwargs.get('slug')
        self.request.session['slug'] = slug

        book = get_object_or_404(Book, slug=slug, status="p")
        ip_address = self.request.user.ip_address
        if ip_address not in book.hits.all():
            book.hits.add(ip_address)
        return book
    
    

class CategoryList(ListView):
    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects(slug=slug))
        return category.book(status='p')
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return category

def categoris(request):
    context = {"category": Category.objects.filter(status=True, parent= None)}
    return render(request, 'category.html', context)

def categorychild(request, slug):
    context = {"category": Category.objects.filter(status=True, slug=slug), "catc": Category.objects.filter(status=True),"categoris": Category.objects.filter(status=True,  slug=slug), "bookis": Book.objects.all()}
    return render(request, 'categorychild.html', context)

def categoryfinal(request, slug):
    context = {"categoris": Category.objects.filter(status=True,  slug=slug), "bookis": Book.objects.all()}
    return render(request, 'categoryfinal.html', context)

def infinity(request):
    return render(request, 'infinity.html')

def request_infinity(request):
    return render(request, 'reqinfinity.html')


def categoryrecent(request):
    context = {"bookis": Book.objects.all()}
    return render(request, 'category_recent_detail.html', context)


def ghav(request):
    return render(request, 'ghav.html')



def oldcomment(request, slug, s=0):
    context = {"commits": Comment.objects.filter(active=True), "booki": Book.objects.filter(status='p', slug=slug)}
    for book in context["booki"]:
        for comment in context["commits"]:
            if comment.book == book:
                s = s + 1
    s = numbers_convertor(str(s))          
                
    context = {"commits": Comment.objects.filter(active=True), "booki": Book.objects.filter(status='p', slug=slug), "s": s}
        
    return render(request, 'oldcomment.html', context)


class Mylogin(LoginView):
     template_name = 'login2.html'
     success_url = reverse_lazy("myapp:login")
     
     





         
         
def post_detail(request, slug):
    template_name = 'newcomment.html'
    book = get_object_or_404(Book, slug=slug)
    comments = book.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.book = book
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'book': book,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})






def popular_books_detail(request):
    last_month = datetime.today()-timedelta(days=30)
    

    return render (request, 'popular_books_detail.html', {'popular_books': Book.objects.annotate(count=Count('hits'), filter=Q(bookhit__created__gt=last_month)).order_by('-count')[:5]})


def hot_books_detail(request):
    last_month = datetime.today()-timedelta(days=30)
    hot_books = Book.objects.annotate(count=Count('comments'), filter=Q(comments__created_on__gt=last_month)).order_by('-count', '-publish')[:5]
           
                            
    return render (request, 'hot_books_detail.html', {'hot_books': hot_books})




def most_stars(request):
    last_month = datetime.today()-timedelta(days=30)
    
    most_stars = Book.objects.annotate(count=Count('hits'), filter=Q(bookhit__created__gt=last_month)).order_by('-count').distinct()[:6]
                            
    return render (request, 'most_stars_detail.html', {'most_stars': most_stars})




class SearchList(ListView):
    model = Book
    template_name = 'search_list.html'

mysite/myapp/templates/categorychild.html
 {% extends 'mybase.html' %}
{% load base_tags %}
{% load static %}
{% comment %} <!doctype html>
<html lang="fa" dir="rtl">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.rtl.min.css" integrity="sha384-+qdLaIRZfNu4cVPK/PxJJEy0B0f3Ugv8i482AKY7gwXwhaCroABd086ybrVKTa0q" crossorigin="anonymous">
    <title> دانلود و خرید کتاب صوتی با طاقچه</title>


    <script>


      var slidePosition = 1;
      SlideShow(slidePosition);
      
      // forward/Back controls
      function plusSlides(n) {
        SlideShow(slidePosition += n);
      }
      
      //  images controls
      function currentSlide(n) {
        SlideShow(slidePosition = n);
      }
      
      function SlideShow(n) {
        var i;
        var slides = document.getElementsByClassName("Containers");
        var circles = document.getElementsByClassName("dots");
        if (n > slides.length) {slidePosition = 1}
        if (n < 1) {slidePosition = slides.length}
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        for (i = 0; i < circles.length; i++) {
            circles[i].className = circles[i].className.replace(" enable", "");
        }
        slides[slidePosition-1].style.display = "block";
        circles[slidePosition-1].className += " enable";
      } 
      

    </script>
  </head>
<body>
    <!-- Navigation-->
    <div class="sticky-top bg-white p-1 ">
        <div calss="container">
        <nav class="navbar navbar-expand-lg navbar-light container">
          <div class="container-fluid">
            <a class="navbar-brand fs-1 font-weight-bold" href="#">طاقچه</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent display-4">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link "  href="{% url 'myapp:categoris' %}" ><p style="font-size:14px">دسته بندی</p></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#"> <p style="font-size:14px">بی نهایت</p></a>
                </li>
        
        
        
                <li class="nav-item">
                    <a class="nav-link" href="#"><p style="font-size:14px">  صوتی</p></a>
                  </li>
                  
        <li>
                <form class="form-inline" action="{% url 'myapp:search' %}">
                    <div class="form-group mx-sm-3 mb-2">
        
                    <div class="container g-0">
                        <div class="row">
                            <div class="col-sm-2 g-0 m-0">
        
                                <button class="text-nowrap  border border-light  mr-5 mb-1 p-0 mt-0 display-inline"><img  class="rounded float-left" src="/media/images/search.png" width="35" height="35"></button>
                                    </div>
                                    <div class="text-nowrap col-sm-10 g-0">
                        <input type="text" name="q" class="form-control" >
                            </div>
                                       </div>
                </div>
                    </form>
        
                </li>
                <div class="position-absolute top-0 end-0">
                    <ul class="navbar-nav container mr-auto">
                        <li class="nav-item active">
                            <h5 class= "border p-2 rounded-pill my-4" style=" font-size: 0.9rem; color:white;  background-color:white">
                              <a href="#" class="text-decoration-none color:white text-center" style="text-align:center"> <p style="font-size:14px">نصب  طاقچه</p></a></h5>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#"> <p style="font-size:14px">&nbsp;&nbsp;&nbsp; ورود</p></a>
                        </li>
                    </ul>
                </div>
               
                  </div>
                </ul>
        
                
          </nav> 
        </div>
        </div>
        </div> {% endcomment %}
     {%block alarm %}   {% endblock %}
     {% block body %}
    <div style="text-align:right"><a href="{% url 'myapp:categoris' %}">برگشت</a></div>
{% for item in category %}
{% if item.slug == 'audio' %}
{% for cat in categoris %}
<div class="container" style="text-align:right">
    {% if cat.mtitle %}
    <h1 style="text-align:center">{{cat.mtitle}}</h1>
    {% else %}
    <h1 style="text-align:center"> {{cat.title}}</h2>
    {% endif %}
    {% if cat.subtitle %}
    <h2 style="text-align:center"> {{cat.psubtitle}}</h2>
    {% endif %}
    {% if cat.description %}

      
    {% comment %} <p id="demo" onclick="myFunction()"> <p style="text-align:center"> <img  src="{% static 'assets/img/download.png' %}"  weight="30" height="30"  ></p></p> {% endcomment %}

    <p class="text-center
    ">
        <a class="btn btn-light text-center" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
<div style="text-align:center">
         <svg xmlns="http://www
         .w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 13.293V1.5A.5.5 0 0 1 8 1z"/>
              </svg>

            </div> 
        </a>
      </p>
      <div class="collapse" id="collapseExample">
        <div class="card card-body">
{{cat.pdescription}}        </div>
      </div>
      
    {% endif %}
   {% for book in bookis %}
   {% if cat.title in book.category_to_list %}




   <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            <div class="post-preview">
                    <img src="{{book.image.url}}">
                    <h2 class="post-title" style="text-align:right;"><a href="{% url 'myapp:detail' book.slug %}">{{book.title}}</a></h2>
                    {% if book.subtitle %}
                    <h3 class="post-subtitle" style="text-align:right">{{book.subtitle}}</h3>
                    {% endif %}
                    

               
                <div class="post-meta">
                    <h4 class="post-subtitle" style="text-align:right">
نویسنده:                          {{book.author}}</h4>
                      </div>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
           
        </div>
    </div>
</div>


   {% endif %}
     {% endfor %}
{% endfor %}

{% else %}
{% for cat in catc %}
{% if cat.parent.title == item.title %}
<div style="text-align:right"><a href="{% url 'myapp:categoryfinal' cat.slug %}">{{cat.title }}</a></div>
<hr style="height:2px;border-width:0;color:gray;background-color:gray">

{% endif %}
{% endfor %}



{% endif %}
{% endfor %}
{% endblock %}
{% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html> {% endcomment %}

mysite/myapp/templates/newu1.html




{% load base_tags %}
{% load static %}
<!doctype html>

<html lang="fa" dir="rtl">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.rtl.min.css" integrity="sha384-+qdLaIRZfNu4cVPK/PxJJEy0B0f3Ugv8i482AKY7gwXwhaCroABd086ybrVKTa0q" crossorigin="anonymous">
    <title> دانلود و خرید کتاب صوتی با طاقچه</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.rtl.min.css" integrity="sha384-+qdLaIRZfNu4cVPK/PxJJEy0B0f3Ugv8i482AKY7gwXwhaCroABd086ybrVKTa0q" crossorigin="anonymous">
  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <script>


      var slidePosition = 1;
      SlideShow(slidePosition);
      
      // forward/Back controls
      function plusSlides(n) {
        SlideShow(slidePosition += n);
      }
      
      //  images controls
      function currentSlide(n) {
        SlideShow(slidePosition = n);
      }
      
      function SlideShow(n) {
        var i;
        var slides = document.getElementsByClassName("Containers");
        var circles = document.getElementsByClassName("dots");
        if (n > slides.length) {slidePosition = 1}
        if (n < 1) {slidePosition = slides.length}
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        for (i = 0; i < circles.length; i++) {
            circles[i].className = circles[i].className.replace(" enable", "");
        }
        slides[slidePosition-1].style.display = "block";
        circles[slidePosition-1].className += " enable";
      } 
      

    </script>
  </head>
  <body>
    {% comment %} <script> alert("این صفحه یک شبیه سازی از سایت طاقچه است");</script> {% endcomment %}
      {% comment %} ********* {% endcomment %}
{% comment %} Navbar {% endcomment %}
<div class="sticky-top bg-white p-1 ">
<div calss="container">
<nav class="navbar navbar-expand-lg navbar-light container">
  <div class="container-fluid">
    <a class="navbar-brand fs-1 font-weight-bold" href="{% url 'myapp:api' %}">طاقچه</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent display-4">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link "  href="{% url 'myapp:categoris' %}" ><p style="font-size:14px">دسته بندی</p></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"> <p style="font-size:14px">بی نهایت</p></a>
        </li>



        <li class="nav-item">
            <a class="nav-link" href="#"><p style="font-size:14px">  صوتی</p></a>
          </li>
          
<li>
        <form class="form-inline" action="{% url 'myapp:search' %}">
            <div class="form-group mx-sm-3 mb-2">

            <div class="container g-0">
                <div class="row">
                    <div class="col-sm-2 g-0 m-0">

                        <button class="text-nowrap  border border-light  mr-5 mb-1 p-0 mt-0 display-inline"><img  class="rounded float-left" src="/media/images/search.png" width="35" height="35"></button>
                            </div>
                            <div class="text-nowrap col-sm-10 g-0">
                <input type="text" name="q" class="form-control" >
                    </div>
                               </div>
        </div>
            </form>

        </li>
        <div class="position-absolute top-0 end-0">
            <ul class="navbar-nav container mr-auto">
                <li class="nav-item active">
                    <h5 class= "border p-2 rounded-pill my-4" style=" font-size: 0.9rem; color:white;  background-color:white">
                      <a href="#" class="text-decoration-none color:white text-center" style="text-align:center"> <p style="font-size:14px">نصب  طاقچه</p></a></h5>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'myapp:login' %}"> <p style="font-size:14px">&nbsp;&nbsp;&nbsp; ورود</p></a>
                </li>
            </ul>
        </div>
       
          </div>
        </ul>

        
  </nav> 
</div>
</div>
</div>
  {% comment %} Endnavbar {% endcomment %}
   <div class="container">
    <div class="row">
        <div class="col-5">
   {% include 'loginslide.html' %}
        </div>
        <div class="col-7 ">
          <div class="align-items-center">
<div class="py-4" style="text-align:center;"><h1>خوش آمدی:)</h1></div>
<form  method="post" action="{% url 'myapp:login2' %}" style="text-align:center;" novalidate>
  {% csrf_token %}
 {{form.as_p}}
<div class="py-4 fs-5"><a class="text-decoration-none" href="{% url 'myapp:ghav' %}">قوانین استفاده از طاقچه
   </a></div>
 <div class=" py-4">
   
  <div class="align-self-center p-3 mx-10 bg-secondary text-dark  rounded rounded-pill " >
    {% comment %} <button type="submit" form="SignupForm" value="ادامه">
    
    <a class="text-decoration-none" href="{% url 'myapp:login2' %}"> ادامه</a>
  
  </button> {% endcomment %}

 <input type="submit" value="ادامه">

  </div>
 </form>
{% comment %} <button  type="submit">ادامه</button> {% endcomment %}
   </div>
  </div>
</div>
</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>

